//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.27 at 01:37:45 PM EST 
//


package Fangore.Engine.Resources.NPC;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NPCMapInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NPCMapInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="MapName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="InitialTileX" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="InitialTileY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NPCMapInfo")
public class NPCMapInfo {

    @XmlAttribute(name = "MapName")
    protected String mapName;
    @XmlAttribute(name = "InitialTileX")
    protected Integer initialTileX;
    @XmlAttribute(name = "InitialTileY")
    protected Integer initialTileY;

    /**
     * Gets the value of the mapName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapName() {
        return mapName;
    }

    /**
     * Sets the value of the mapName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapName(String value) {
        this.mapName = value;
    }

    /**
     * Gets the value of the initialTileX property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialTileX() {
        return initialTileX;
    }

    /**
     * Sets the value of the initialTileX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialTileX(Integer value) {
        this.initialTileX = value;
    }

    /**
     * Gets the value of the initialTileY property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getInitialTileY() {
        return initialTileY;
    }

    /**
     * Sets the value of the initialTileY property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setInitialTileY(Integer value) {
        this.initialTileY = value;
    }

}
