//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.27 at 01:37:45 PM EST 
//


package Fangore.Engine.Resources.NPC;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Fangore.Engine.Resources.NPC package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NPCs_QNAME = new QName("", "NPCs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Fangore.Engine.Resources.NPC
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NPCMapInfo }
     * 
     */
    public NPCMapInfo createNPCMapInfo() {
        return new NPCMapInfo();
    }

    /**
     * Create an instance of {@link NPCType }
     * 
     */
    public NPCType createNPCType() {
        return new NPCType();
    }

    /**
     * Create an instance of {@link NPCListType }
     * 
     */
    public NPCListType createNPCListType() {
        return new NPCListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NPCListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NPCs")
    public JAXBElement<NPCListType> createNPCs(NPCListType value) {
        return new JAXBElement<NPCListType>(_NPCs_QNAME, NPCListType.class, null, value);
    }

}
